### ISSUE TITLE
临界急冻雪球可让冒险模式玩家放雪

### ISSUE THREAD

**Issue by njh197** [linngdu664/Better-Snowball-Fight3-mod#1]
如题（

**Comment by linngdu664** [comment]
感觉这并不算是mod的问题，我不觉得让冒险模式玩家可以放雪是不应该的。我猜你是在teacon遇见的这个问题，其实为了防止影响到其他展馆，我之前给茶馆员工提过用actrl在我展馆领地外的全部区域禁用的，不过他们忘了而已。而且每天展示服都会重置，不必担心雪去不掉。
